[build-system]
requires = ["setuptools>=65.5.1", "wheel>=0.38.4"]
build-backend = "setuptools.build_meta"

[project]
name = "nlsql"
version = "0.1.0"
description = "Natural Language to SQL Query System"
requires-python = ">=3.10" 